### Create a policy
POST https://localhost:7239/policies
Content-Type: application/json

{
  "policyNumber" : "PL112{{$random.integer()}}",
  "policyHolder" : "Kevin Smith",
  "premium": {{$random.integer()}}
}

###

### Get policies with filter
GET https://localhost:7239/policies?policyNumber=PL112168

###

### Get single policy
GET https://localhost:7239/policies/bd5d6ec8-1540-4cc0-a7c1-191ebb92c81c

###

### Create a claim for a policy
POST https://localhost:7239/policies/bd5d6ec8-1540-4cc0-a7c1-191ebb92c81c/claims
Content-Type: application/json

{
  "amount" : 199.22,
  "description" : "Water leak in the kitchen"
}