### Create a policy
# @name postPolicies
POST https://localhost:7281/policies
Content-Type: application/json

{
  "policyNumber" : "PL12345{{$random.integer()}}",
  "policyHolder" : "Kevin Smith",
  "premium": {{$random.integer()}}
}

###

### Get policies with filter
GET https://localhost:7281/policies?policyNumber=PL12345385

###

### Get single policy
GET https://localhost:7281/policies/d74ca913-9a07-4c08-b4c8-f25dcafdac81

###

### Create a claim for a policy
POST https://localhost:7281/policies/d74ca913-9a07-4c08-b4c8-f25dcafdac81/claims
Content-Type: application/json

{
  "amount" : 199.22,
  "description" : "Water leak in the kitchen"
}